imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true
    translator:      { fallback: %locale% }

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    filters:
        lessphp:
             file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
             apply_to: "\.less$"
        cssrewrite: ~
braincrafted_bootstrap:
    less_filter: lessphp

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

services:
   ath_student_registration:
      class: Ath\UserBundle\Form\Type\RegistrationStudentFormType
      argument: %fos_user.model.user.class%
      tags:
         -  { name: form.type }

# Ath/UserBundle/Resources/config/config.yml
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Ath\UserBundle\Entity\Utilisateur
    service:
        user_manager: pugx_user_manager

pugx_multi_user:
    users:
        student:
            entity:
                class: Ath\UserBundle\Entity\Student
            registration:
                form:
                    type: Ath\UserBundle\Form\Type\RegistrationStudentFormType
                    name: fos_student_registration_form
                    validation_groups:  [Registration, Default]
                template: AthUserBundle:Registration:student.form.html.twig
            profile:
                form:
                    type: Ath\UserBundle\Form\Type\ProfileStudentFormType
                    name: fos_student_profile_form
                    validation_groups:  [Profile, Default]

        professor:
            entity:
                class: Ath\UserBundle\Entity\Professor
            registration:
                form:
                    type: Ath\UserBundle\Form\Type\RegistrationProfessorFormType
                    name: fos_professor_registration_form
                    validation_groups:  [Registration, Default]
                template: AthUserBundle:Registration:professor.form.html.twig
            profile:
                form:
                    type: Ath\UserBundle\Form\Type\ProfileProfessorFormType
                    name: fos_professor_profile_form
                    validation_groups:  [Profile, Default]

        administrator:
            entity:
                class: Ath\UserBundle\Entity\Administrator
            registration:
                form:
                    type: Ath\UserBundle\Form\Type\RegistrationAdministratorFormType
                    name: fos_administrator_registration_form
                    validation_groups:  [Registration, Default]
                template: AthUserBundle:Registration:administrator.form.html.twig
            profile:
                form:
                    type: Ath\UserBundle\Form\Type\ProfileAdministratorFormType
                    name: fos_administrator_profile_form
                    validation_groups:  [Profile, Default]


fos_js_routing:
    routes_to_expose: [ath_exercise_get_all, ath_exercise_levels, ath_exercise_init, ath_exercise_subject_view, ath_exercise_blank_view, ath_exercise_get_data, ath_exercise_get_subject_view, ath_exercise_check_answers, ath_exercise_get_create_view, ath_exercise_set_exercise, ath_exercise_admin]
