ath_note:
    resource: "@AthNoteBundle/Resources/config/routing.yml"
    prefix:   /

ath_cours:
    resource: "@AthCoursBundle/Resources/config/routing.yml"
    prefix:   /

ath_page:
    resource: "@AthPageBundle/Resources/config/routing.yml"
    prefix:   /

ath_user:
    resource: "@AthUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
